version: '3.9'

services:
  backend:
    image: karthiknamboori/rule-engine-backend:latest  
    container_name: flask_app
    ports:
      - "5555:5555"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
    restart: always

  frontend:
    image: karthiknamboori/rule-engine-frontend:latest 
    container_name: react_client
    ports:
      - "3000:80"  # Nginx serves the React app on port 80 inside the container
    restart: always

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:

