version: '3.9'

services:
  # web:
  #   build: .
  #   container_name: flask_app
  #   command: python app.py
  #   volumes:
  #     - ./:/app/
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   environment:
  #     # DATABASE_URI is no longer needed since it's hard-coded
  #     # If you decide to use environment variables in the future, uncomment the line below
  #     # - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
  #   restart: always

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
